name: Run Regression Tests

on:
  workflow_dispatch:
  pull_request:

env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
    LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}

jobs:
  run_evaluation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run evaluation
        run: python test_chain.py
