name: Run Evaluation

on:
    workflow_dispatch:

env:
    POETRY_VERSION: "1.4.2"
    VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
    VOYAGE_AI_MODEL: ${{ secrets.VOYAGE_AI_MODEL }}
    WEAVIATE_API_KEY: ${{ secrets.WEAVIATE_API_KEY }}
    WEAVIATE_URL: ${{ secrets.WEAVIATE_URL }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
    LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}

jobs:
    run_evaluation:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
                cache: "pip"
            - name: Install poetry
              run: pipx install poetry==$POETRY_VERSION
            - name: Install dependencies
              run: poetry install --with dev
            - name: Run evaluation
              run: poetry run python -m eval.test_chain
